openapi: 3.0.3
info:
  title: ISO 8583 Messages API
  description: |
    API REST pour la gestion des messages ISO 8583.
    Cette API permet de créer, lire et supprimer des messages ISO 8583 
    avec chiffrement des données sensibles comme le PAN.
  version: 1.0.0
  contact:
    name: Support API
    email: support@example.com

servers:
  - url: http://localhost/api
    description: Serveur de développement
  - url: https://your-domain.com/api
    description: Serveur de production

security:
  - BearerAuth: []

paths:
  /messages:
    get:
      summary: Récupérer la liste des messages ISO 8583
      description: Retourne une liste paginée des messages ISO 8583 avec le PAN masqué pour la sécurité
      tags:
        - Messages
      parameters:
        - name: page
          in: query
          description: Numéro de la page (commence à 1)
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
        - name: limit
          in: query
          description: Nombre d'éléments par page
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
      responses:
        '200':
          description: Liste des messages récupérée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/IsoMessageList'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Créer un nouveau message ISO 8583
      description: Crée un nouveau message ISO 8583 à partir d'un fichier XML
      tags:
        - Messages
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                xml_file:
                  type: string
                  format: binary
                  description: Fichier XML contenant les données du message ISO 8583
              required:
                - xml_file
      responses:
        '201':
          description: Message créé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Message created successfully."
                  id:
                    type: integer
                    example: 123
        '400':
          description: Erreur de validation ou de parsing XML
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '503':
          description: Erreur de service - Impossible de créer le message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /messages/{id}:
    get:
      summary: Récupérer un message ISO 8583 spécifique
      description: Retourne les détails complets d'un message ISO 8583 par son ID, incluant le PAN déchiffré
      tags:
        - Messages
      parameters:
        - name: id
          in: path
          required: true
          description: ID unique du message ISO 8583
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Message récupéré avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsoMessageDetail'
        '404':
          description: Message non trouvé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    delete:
      summary: Supprimer un message ISO 8583
      description: Supprime définitivement un message ISO 8583 de la base de données
      tags:
        - Messages
      parameters:
        - name: id
          in: path
          required: true
          description: ID unique du message ISO 8583 à supprimer
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Message supprimé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Message deleted successfully."
        '400':
          description: ID de message invalide
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '503':
          description: Impossible de supprimer le message
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token d'authentification Bearer

  schemas:
    IsoMessageList:
      type: object
      properties:
        id:
          type: integer
          description: ID unique du message
          example: 123
        mti:
          type: string
          description: Message Type Identifier (MTI)
          example: "0200"
        pan:
          type: string
          description: Primary Account Number (PAN) masqué pour la sécurité
          example: "1234****5678"
        processing_code:
          type: string
          description: Code de traitement de la transaction
          example: "000000"
        amount:
          type: integer
          description: Montant de la transaction (en centimes)
          example: 10000
        transaction_time:
          type: string
          description: Heure de la transaction (HHMMSS)
          example: "143022"
        transaction_date:
          type: string
          description: Date de la transaction (MMDD)
          example: "0815"
        rrn:
          type: string
          description: Retrieval Reference Number
          example: "123456789012"
        response_code:
          type: string
          description: Code de réponse de la transaction
          example: "00"
        terminal_id:
          type: string
          description: Identifiant du terminal
          example: "12345678"
        currency:
          type: string
          description: Code devise (ISO 4217)
          example: "978"
        created_at:
          type: string
          format: date-time
          description: Date et heure de création du message
          example: "2024-08-19T14:30:22Z"

    IsoMessageDetail:
      allOf:
        - $ref: '#/components/schemas/IsoMessageList'
        - type: object
          properties:
            pan_full:
              type: string
              description: Primary Account Number (PAN) complet déchiffré (accès autorisé uniquement)
              example: "1234567890123456"

    Pagination:
      type: object
      properties:
        page:
          type: integer
          description: Numéro de la page courante
          example: 1
        limit:
          type: integer
          description: Nombre d'éléments par page
          example: 10
        total:
          type: integer
          description: Nombre total d'éléments
          example: 250
        total_pages:
          type: integer
          description: Nombre total de pages
          example: 25

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Message d'erreur
          example: "Message not found."
        debug:
          type: object
          description: Informations de débogage (uniquement en développement)
          nullable: true

  responses:
    UnauthorizedError:
      description: Token d'authentification manquant ou invalide
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    
    InternalServerError:
      description: Erreur interne du serveur
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  examples:
    IsoMessageExample:
      summary: Exemple de message ISO 8583
      value:
        id: 123
        mti: "0200"
        pan: "1234****5678"
        processing_code: "000000"
        amount: 10000
        transaction_time: "143022"
        transaction_date: "0815"
        rrn: "123456789012"
        response_code: "00"
        terminal_id: "12345678"
        currency: "978"
        created_at: "2024-08-19T14:30:22Z"

tags:
  - name: Messages
    description: Opérations CRUD sur les messages ISO 8583